import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const hiraganaCards = [
  { kana: "あ", romaji: "a",  meaning: "a" },
  { kana: "い", romaji: "i",  meaning: "i" },
  { kana: "う", romaji: "u",  meaning: "u" },
  { kana: "え", romaji: "e",  meaning: "e" },
  { kana: "お", romaji: "o",  meaning: "o" },
  { kana: "か", romaji: "ka", meaning: "ka" },
  { kana: "き", romaji: "ki", meaning: "ki" },
  { kana: "く", romaji: "ku", meaning: "ku" },
  { kana: "け", romaji: "ke", meaning: "ke" },
  { kana: "こ", romaji: "ko", meaning: "ko" },
  { kana: "さ", romaji: "sa", meaning: "sa" },
  { kana: "し", romaji: "shi", meaning: "shi" },
  { kana: "す", romaji: "su", meaning: "su" },
  { kana: "せ", romaji: "se", meaning: "se" },
  { kana: "そ", romaji: "so", meaning: "so" },
  { kana: "た", romaji: "ta", meaning: "ta" },
  { kana: "ち", romaji: "chi", meaning: "chi" },
  { kana: "つ", romaji: "tsu", meaning: "tsu" },
  { kana: "て", romaji: "te", meaning: "te" },
  { kana: "と", romaji: "to", meaning: "to" },
  { kana: "な", romaji: "na", meaning: "na" },
  { kana: "に", romaji: "ni", meaning: "ni" },
  { kana: "ぬ", romaji: "nu", meaning: "nu" },
  { kana: "ね", romaji: "ne", meaning: "ne" },
  { kana: "の", romaji: "no", meaning: "no" },
  { kana: "は", romaji: "ha", meaning: "ha" },
  { kana: "ひ", romaji: "hi", meaning: "hi" },
  { kana: "ふ", romaji: "fu", meaning: "fu" },
  { kana: "へ", romaji: "he", meaning: "he" },
  { kana: "ほ", romaji: "ho", meaning: "ho" },
  { kana: "ま", romaji: "ma", meaning: "ma" },
  { kana: "み", romaji: "mi", meaning: "mi" },
  { kana: "む", romaji: "mu", meaning: "mu" },
  { kana: "め", romaji: "me", meaning: "me" },
  { kana: "も", romaji: "mo", meaning: "mo" },
  { kana: "や", romaji: "ya", meaning: "ya" },
  { kana: "ゆ", romaji: "yu", meaning: "yu" },
  { kana: "よ", romaji: "yo", meaning: "yo" },
  { kana: "ら", romaji: "ra", meaning: "ra" },
  { kana: "り", romaji: "ri", meaning: "ri" },
  { kana: "る", romaji: "ru", meaning: "ru" },
  { kana: "れ", romaji: "re", meaning: "re" },
  { kana: "ろ", romaji: "ro", meaning: "ro" },
  { kana: "わ", romaji: "wa", meaning: "wa" },
  { kana: "を", romaji: "wo", meaning: "wo" },
  { kana: "ん", romaji: "n",  meaning: "n" },
];

const katakanaCards = [
  { kana: "ア", romaji: "a",  meaning: "a" },
  { kana: "イ", romaji: "i",  meaning: "i" },
  { kana: "ウ", romaji: "u",  meaning: "u" },
  { kana: "エ", romaji: "e",  meaning: "e" },
  { kana: "オ", romaji: "o",  meaning: "o" },
  { kana: "カ", romaji: "ka", meaning: "ka" },
  { kana: "キ", romaji: "ki", meaning: "ki" },
  { kana: "ク", romaji: "ku", meaning: "ku" },
  { kana: "ケ", romaji: "ke", meaning: "ke" },
  { kana: "コ", romaji: "ko", meaning: "ko" },
  { kana: "サ", romaji: "sa", meaning: "sa" },
  { kana: "シ", romaji: "shi", meaning: "shi" },
  { kana: "ス", romaji: "su", meaning: "su" },
  { kana: "セ", romaji: "se", meaning: "se" },
  { kana: "ソ", romaji: "so", meaning: "so" },
  { kana: "タ", romaji: "ta", meaning: "ta" },
  { kana: "チ", romaji: "chi", meaning: "chi" },
  { kana: "ツ", romaji: "tsu", meaning: "tsu" },
  { kana: "テ", romaji: "te", meaning: "te" },
  { kana: "ト", romaji: "to", meaning: "to" },
  { kana: "ナ", romaji: "na", meaning: "na" },
  { kana: "ニ", romaji: "ni", meaning: "ni" },
  { kana: "ヌ", romaji: "nu", meaning: "nu" },
  { kana: "ネ", romaji: "ne", meaning: "ne" },
  { kana: "ノ", romaji: "no", meaning: "no" },
  { kana: "ハ", romaji: "ha", meaning: "ha" },
  { kana: "ヒ", romaji: "hi", meaning: "hi" },
  { kana: "フ", romaji: "fu", meaning: "fu" },
  { kana: "ヘ", romaji: "he", meaning: "he" },
  { kana: "ホ", romaji: "ho", meaning: "ho" },
  { kana: "マ", romaji: "ma", meaning: "ma" },
  { kana: "ミ", romaji: "mi", meaning: "mi" },
  { kana: "ム", romaji: "mu", meaning: "mu" },
  { kana: "メ", romaji: "me", meaning: "me" },
  { kana: "モ", romaji: "mo", meaning: "mo" },
  { kana: "ヤ", romaji: "ya", meaning: "ya" },
  { kana: "ユ", romaji: "yu", meaning: "yu" },
  { kana: "ヨ", romaji: "yo", meaning: "yo" },
  { kana: "ラ", romaji: "ra", meaning: "ra" },
  { kana: "リ", romaji: "ri", meaning: "ri" },
  { kana: "ル", romaji: "ru", meaning: "ru" },
  { kana: "レ", romaji: "re", meaning: "re" },
  { kana: "ロ", romaji: "ro", meaning: "ro" },
  { kana: "ワ", romaji: "wa", meaning: "wa" },
  { kana: "ヲ", romaji: "wo", meaning: "wo" },
  { kana: "ン", romaji: "n",  meaning: "n" },
];

const kanjiData = [
  // ── N5 ──────────────────────────────────────────────────────────────────
  { character: "一", meaning: "one",           onyomi: "いち、いつ",       kunyomi: "ひと",           strokeCount: 1,  jlptLevel: "N5" },
  { character: "二", meaning: "two",           onyomi: "に、じ",           kunyomi: "ふた",           strokeCount: 2,  jlptLevel: "N5" },
  { character: "三", meaning: "three",         onyomi: "さん、ざん",       kunyomi: "み、みっ",       strokeCount: 3,  jlptLevel: "N5" },
  { character: "四", meaning: "four",          onyomi: "し",               kunyomi: "よ、よっ",       strokeCount: 5,  jlptLevel: "N5" },
  { character: "五", meaning: "five",          onyomi: "ご",               kunyomi: "いつ",           strokeCount: 4,  jlptLevel: "N5" },
  { character: "六", meaning: "six",           onyomi: "ろく",             kunyomi: "む、むっ",       strokeCount: 4,  jlptLevel: "N5" },
  { character: "七", meaning: "seven",         onyomi: "しち",             kunyomi: "なな",           strokeCount: 2,  jlptLevel: "N5" },
  { character: "八", meaning: "eight",         onyomi: "はち",             kunyomi: "や、やっ",       strokeCount: 2,  jlptLevel: "N5" },
  { character: "九", meaning: "nine",          onyomi: "く、きゅう",       kunyomi: "ここの",         strokeCount: 2,  jlptLevel: "N5" },
  { character: "十", meaning: "ten",           onyomi: "じゅう、じっ",     kunyomi: "とお",           strokeCount: 2,  jlptLevel: "N5" },
  { character: "百", meaning: "hundred",       onyomi: "ひゃく",           kunyomi: "—",              strokeCount: 6,  jlptLevel: "N5" },
  { character: "千", meaning: "thousand",      onyomi: "せん",             kunyomi: "ち",             strokeCount: 3,  jlptLevel: "N5" },
  { character: "万", meaning: "ten thousand",  onyomi: "まん、ばん",       kunyomi: "—",              strokeCount: 3,  jlptLevel: "N5" },
  { character: "日", meaning: "day, sun",      onyomi: "にち、じつ",       kunyomi: "ひ、か",         strokeCount: 4,  jlptLevel: "N5" },
  { character: "月", meaning: "moon, month",   onyomi: "げつ、がつ",       kunyomi: "つき",           strokeCount: 4,  jlptLevel: "N5" },
  { character: "火", meaning: "fire",          onyomi: "か",               kunyomi: "ひ",             strokeCount: 4,  jlptLevel: "N5" },
  { character: "水", meaning: "water",         onyomi: "すい",             kunyomi: "みず",           strokeCount: 4,  jlptLevel: "N5" },
  { character: "木", meaning: "tree, wood",    onyomi: "もく、ぼく",       kunyomi: "き、こ",         strokeCount: 4,  jlptLevel: "N5" },
  { character: "金", meaning: "gold, money",   onyomi: "きん、こん",       kunyomi: "かね、かな",     strokeCount: 8,  jlptLevel: "N5" },
  { character: "土", meaning: "earth, soil",   onyomi: "ど、と",           kunyomi: "つち",           strokeCount: 3,  jlptLevel: "N5" },
  { character: "山", meaning: "mountain",      onyomi: "さん、ざん",       kunyomi: "やま",           strokeCount: 3,  jlptLevel: "N5" },
  { character: "川", meaning: "river",         onyomi: "せん",             kunyomi: "かわ",           strokeCount: 3,  jlptLevel: "N5" },
  { character: "田", meaning: "rice field",    onyomi: "でん",             kunyomi: "た",             strokeCount: 5,  jlptLevel: "N5" },
  { character: "人", meaning: "person",        onyomi: "じん、にん",       kunyomi: "ひと",           strokeCount: 2,  jlptLevel: "N5" },
  { character: "口", meaning: "mouth",         onyomi: "こう、く",         kunyomi: "くち",           strokeCount: 3,  jlptLevel: "N5" },
  { character: "目", meaning: "eye",           onyomi: "もく、ぼく",       kunyomi: "め、ま",         strokeCount: 5,  jlptLevel: "N5" },
  { character: "耳", meaning: "ear",           onyomi: "じ",               kunyomi: "みみ",           strokeCount: 6,  jlptLevel: "N5" },
  { character: "手", meaning: "hand",          onyomi: "しゅ",             kunyomi: "て",             strokeCount: 4,  jlptLevel: "N5" },
  { character: "足", meaning: "foot, leg",     onyomi: "そく",             kunyomi: "あし、た",       strokeCount: 7,  jlptLevel: "N5" },
  { character: "上", meaning: "above, up",     onyomi: "じょう、しょう",   kunyomi: "うえ、うわ、かみ", strokeCount: 3, jlptLevel: "N5" },
  { character: "下", meaning: "below, down",   onyomi: "か、げ",           kunyomi: "した、しも、もと", strokeCount: 3, jlptLevel: "N5" },
  { character: "中", meaning: "middle, inside", onyomi: "ちゅう",          kunyomi: "なか",           strokeCount: 4,  jlptLevel: "N5" },
  { character: "大", meaning: "big, large",    onyomi: "だい、たい",       kunyomi: "おお",           strokeCount: 3,  jlptLevel: "N5" },
  { character: "小", meaning: "small, little", onyomi: "しょう",           kunyomi: "ちい、こ、お",   strokeCount: 3,  jlptLevel: "N5" },
  { character: "本", meaning: "book, origin",  onyomi: "ほん",             kunyomi: "もと",           strokeCount: 5,  jlptLevel: "N5" },
  { character: "学", meaning: "study, learn",  onyomi: "がく",             kunyomi: "まな",           strokeCount: 8,  jlptLevel: "N5" },
  { character: "校", meaning: "school",        onyomi: "こう",             kunyomi: "—",              strokeCount: 10, jlptLevel: "N5" },
  { character: "先", meaning: "ahead, previous", onyomi: "せん",           kunyomi: "さき",           strokeCount: 6,  jlptLevel: "N5" },
  { character: "生", meaning: "life, birth",   onyomi: "せい、しょう",     kunyomi: "い、う、は、お", strokeCount: 5,  jlptLevel: "N5" },
  { character: "何", meaning: "what",          onyomi: "か",               kunyomi: "なに、なん",     strokeCount: 7,  jlptLevel: "N5" },
  { character: "国", meaning: "country",       onyomi: "こく",             kunyomi: "くに",           strokeCount: 8,  jlptLevel: "N5" },
  { character: "年", meaning: "year",          onyomi: "ねん",             kunyomi: "とし",           strokeCount: 6,  jlptLevel: "N5" },
  { character: "見", meaning: "see, look",     onyomi: "けん",             kunyomi: "み",             strokeCount: 7,  jlptLevel: "N5" },
  { character: "聞", meaning: "hear, listen",  onyomi: "ぶん、もん",       kunyomi: "き、きこ",       strokeCount: 14, jlptLevel: "N5" },
  { character: "話", meaning: "talk, speech",  onyomi: "わ",               kunyomi: "はな、はなし",   strokeCount: 13, jlptLevel: "N5" },
  { character: "食", meaning: "eat, food",     onyomi: "しょく、じき",     kunyomi: "た、く",         strokeCount: 9,  jlptLevel: "N5" },
  { character: "飲", meaning: "drink",         onyomi: "いん",             kunyomi: "の",             strokeCount: 12, jlptLevel: "N5" },
  { character: "来", meaning: "come",          onyomi: "らい",             kunyomi: "く、き、こ",     strokeCount: 7,  jlptLevel: "N5" },
  { character: "行", meaning: "go, carry out", onyomi: "こう、ぎょう、あん", kunyomi: "い、ゆ、おこな", strokeCount: 6, jlptLevel: "N5" },
  { character: "買", meaning: "buy",           onyomi: "ばい",             kunyomi: "か",             strokeCount: 12, jlptLevel: "N5" },
  { character: "書", meaning: "write",         onyomi: "しょ",             kunyomi: "か",             strokeCount: 10, jlptLevel: "N5" },
  { character: "読", meaning: "read",          onyomi: "どく、とく、とう", kunyomi: "よ",             strokeCount: 14, jlptLevel: "N5" },
  { character: "電", meaning: "electricity",   onyomi: "でん",             kunyomi: "—",              strokeCount: 13, jlptLevel: "N5" },
  { character: "車", meaning: "car, vehicle",  onyomi: "しゃ",             kunyomi: "くるま",         strokeCount: 7,  jlptLevel: "N5" },
  { character: "語", meaning: "language, word", onyomi: "ご",              kunyomi: "かた",           strokeCount: 14, jlptLevel: "N5" },
  { character: "右", meaning: "right",         onyomi: "ゆう、う",         kunyomi: "みぎ",           strokeCount: 5,  jlptLevel: "N5" },
  { character: "左", meaning: "left",          onyomi: "さ",               kunyomi: "ひだり",         strokeCount: 5,  jlptLevel: "N5" },
  { character: "前", meaning: "front, before", onyomi: "ぜん",             kunyomi: "まえ",           strokeCount: 9,  jlptLevel: "N5" },
  { character: "後", meaning: "after, back",   onyomi: "ご、こう",         kunyomi: "うし、あと、のち", strokeCount: 9, jlptLevel: "N5" },
  { character: "東", meaning: "east",          onyomi: "とう",             kunyomi: "ひがし",         strokeCount: 8,  jlptLevel: "N5" },
  { character: "西", meaning: "west",          onyomi: "せい、さい",       kunyomi: "にし",           strokeCount: 6,  jlptLevel: "N5" },
  { character: "南", meaning: "south",         onyomi: "なん、な",         kunyomi: "みなみ",         strokeCount: 9,  jlptLevel: "N5" },
  { character: "北", meaning: "north",         onyomi: "ほく",             kunyomi: "きた",           strokeCount: 5,  jlptLevel: "N5" },
  { character: "白", meaning: "white",         onyomi: "はく、びゃく",     kunyomi: "しろ、しら",     strokeCount: 5,  jlptLevel: "N5" },
  { character: "黒", meaning: "black",         onyomi: "こく",             kunyomi: "くろ",           strokeCount: 11, jlptLevel: "N5" },
  { character: "赤", meaning: "red",           onyomi: "せき、しゃく",     kunyomi: "あか",           strokeCount: 7,  jlptLevel: "N5" },
  { character: "青", meaning: "blue, green",   onyomi: "せい、しょう",     kunyomi: "あお",           strokeCount: 8,  jlptLevel: "N5" },
  { character: "高", meaning: "high, expensive", onyomi: "こう",           kunyomi: "たか",           strokeCount: 10, jlptLevel: "N5" },
  { character: "安", meaning: "cheap, safe",   onyomi: "あん",             kunyomi: "やす",           strokeCount: 6,  jlptLevel: "N5" },
  { character: "新", meaning: "new",           onyomi: "しん",             kunyomi: "あたら、あら、にい", strokeCount: 13, jlptLevel: "N5" },
  { character: "古", meaning: "old, ancient",  onyomi: "こ",               kunyomi: "ふる",           strokeCount: 5,  jlptLevel: "N5" },
  { character: "長", meaning: "long, chief",   onyomi: "ちょう",           kunyomi: "なが",           strokeCount: 8,  jlptLevel: "N5" },
  { character: "半", meaning: "half",          onyomi: "はん",             kunyomi: "なか",           strokeCount: 5,  jlptLevel: "N5" },
  { character: "時", meaning: "time, hour",    onyomi: "じ",               kunyomi: "とき",           strokeCount: 10, jlptLevel: "N5" },
  { character: "分", meaning: "minute, part",  onyomi: "ぶん、ふん、ぶ",   kunyomi: "わ",             strokeCount: 4,  jlptLevel: "N5" },
  { character: "男", meaning: "man, male",     onyomi: "だん、なん",       kunyomi: "おとこ",         strokeCount: 7,  jlptLevel: "N5" },
  { character: "女", meaning: "woman, female", onyomi: "じょ、にょ",       kunyomi: "おんな、め",     strokeCount: 3,  jlptLevel: "N5" },
  { character: "子", meaning: "child",         onyomi: "し、す",           kunyomi: "こ",             strokeCount: 3,  jlptLevel: "N5" },
  { character: "父", meaning: "father",        onyomi: "ふ",               kunyomi: "ちち",           strokeCount: 4,  jlptLevel: "N5" },
  { character: "母", meaning: "mother",        onyomi: "ぼ",               kunyomi: "はは",           strokeCount: 5,  jlptLevel: "N5" },
  // ── N4 ──────────────────────────────────────────────────────────────────
  { character: "会", meaning: "meet, assembly", onyomi: "かい、え",        kunyomi: "あ",             strokeCount: 6,  jlptLevel: "N4" },
  { character: "開", meaning: "open",          onyomi: "かい",             kunyomi: "あ、ひら",       strokeCount: 12, jlptLevel: "N4" },
  { character: "思", meaning: "think",         onyomi: "し",               kunyomi: "おも",           strokeCount: 9,  jlptLevel: "N4" },
  { character: "知", meaning: "know",          onyomi: "ち",               kunyomi: "し",             strokeCount: 8,  jlptLevel: "N4" },
  { character: "使", meaning: "use",           onyomi: "し",               kunyomi: "つか",           strokeCount: 8,  jlptLevel: "N4" },
  { character: "作", meaning: "make, create",  onyomi: "さく、さ",         kunyomi: "つく",           strokeCount: 7,  jlptLevel: "N4" },
  { character: "方", meaning: "direction, way", onyomi: "ほう",            kunyomi: "かた",           strokeCount: 4,  jlptLevel: "N4" },
  { character: "今", meaning: "now, present",  onyomi: "こん、きん",       kunyomi: "いま",           strokeCount: 4,  jlptLevel: "N4" },
  { character: "外", meaning: "outside",       onyomi: "がい、げ",         kunyomi: "そと、ほか",     strokeCount: 5,  jlptLevel: "N4" },
  { character: "多", meaning: "many, much",    onyomi: "た",               kunyomi: "おお",           strokeCount: 6,  jlptLevel: "N4" },
  { character: "少", meaning: "few, little",   onyomi: "しょう",           kunyomi: "すく、すこ",     strokeCount: 4,  jlptLevel: "N4" },
  { character: "家", meaning: "house, home",   onyomi: "か、け",           kunyomi: "いえ、や",       strokeCount: 10, jlptLevel: "N4" },
  { character: "間", meaning: "interval, space", onyomi: "かん、けん",     kunyomi: "あいだ、ま",     strokeCount: 12, jlptLevel: "N4" },
  { character: "強", meaning: "strong",        onyomi: "きょう、ごう",     kunyomi: "つよ、し",       strokeCount: 11, jlptLevel: "N4" },
  { character: "弱", meaning: "weak",          onyomi: "じゃく",           kunyomi: "よわ",           strokeCount: 10, jlptLevel: "N4" },
  { character: "医", meaning: "medicine, doctor", onyomi: "い",            kunyomi: "—",              strokeCount: 7,  jlptLevel: "N4" },
  { character: "病", meaning: "illness, sick", onyomi: "びょう、へい",     kunyomi: "やまい、や",     strokeCount: 10, jlptLevel: "N4" },
  { character: "駅", meaning: "station",       onyomi: "えき",             kunyomi: "—",              strokeCount: 14, jlptLevel: "N4" },
  { character: "近", meaning: "near, close",   onyomi: "きん",             kunyomi: "ちか",           strokeCount: 7,  jlptLevel: "N4" },
  { character: "遠", meaning: "far, distant",  onyomi: "えん、おん",       kunyomi: "とお",           strokeCount: 13, jlptLevel: "N4" },
  { character: "明", meaning: "bright, clear", onyomi: "めい、みょう",     kunyomi: "あか、あき、あく", strokeCount: 8, jlptLevel: "N4" },
  { character: "暗", meaning: "dark, gloomy",  onyomi: "あん",             kunyomi: "くら",           strokeCount: 13, jlptLevel: "N4" },
  { character: "重", meaning: "heavy, pile",   onyomi: "じゅう、ちょう",   kunyomi: "おも、かさ",     strokeCount: 9,  jlptLevel: "N4" },
  { character: "軽", meaning: "light, easy",   onyomi: "けい",             kunyomi: "かる、かろ",     strokeCount: 12, jlptLevel: "N4" },
  { character: "広", meaning: "wide, broad",   onyomi: "こう",             kunyomi: "ひろ",           strokeCount: 5,  jlptLevel: "N4" },
  { character: "太", meaning: "fat, thick",    onyomi: "た、たい",         kunyomi: "ふと",           strokeCount: 4,  jlptLevel: "N4" },
  { character: "細", meaning: "thin, slender", onyomi: "さい",             kunyomi: "ほそ、こま",     strokeCount: 11, jlptLevel: "N4" },
  { character: "早", meaning: "early, fast",   onyomi: "そう、さっ",       kunyomi: "はや",           strokeCount: 6,  jlptLevel: "N4" },
  { character: "遅", meaning: "late, slow",    onyomi: "ち",               kunyomi: "おそ",           strokeCount: 12, jlptLevel: "N4" },
  { character: "音", meaning: "sound, noise",  onyomi: "おん、いん",       kunyomi: "おと、ね",       strokeCount: 9,  jlptLevel: "N4" },
];

async function main() {
  // Kana lessons
  const lessons = [
    {
      slug: "hiragana-basics",
      title: "Hiragana",
      description: "The 46 basic hiragana characters.",
      cards: hiraganaCards,
    },
    {
      slug: "katakana-basics",
      title: "Katakana",
      description: "The 46 basic katakana characters.",
      cards: katakanaCards,
    },
  ];

  for (const lesson of lessons) {
    await prisma.lesson.upsert({
      where: { slug: lesson.slug },
      update: { title: lesson.title, description: lesson.description },
      create: {
        slug: lesson.slug,
        title: lesson.title,
        description: lesson.description,
        cards: { create: lesson.cards },
      },
    });
  }

  // Kanji
  for (const k of kanjiData) {
    await prisma.kanji.upsert({
      where: { character: k.character },
      update: k,
      create: k,
    });
  }

  console.log(`Seeded ${lessons.length} lessons and ${kanjiData.length} kanji.`);
}

main()
  .then(async () => { await prisma.$disconnect(); })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
